package com.tva.myownaccount;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

public class myOwnAccount {

  private static final Logger logger = LogManager.getLogger(myOwnAccount.class.getName());

  
  public static void myOwnAccountSampleMethod() {
    logger.info("Sample method generated by maven archetype");
    System.out.println("Sample method generated by maven archetype");
  }
}
